Checkpoint
TieBeTie/Encoder pull request #1
Opened 2020-04-20 13:12 UTC by TieBeTie

2020-04-21 22:21 UTC, WokinShopash requested changes

2020-04-21 22:21 UTC, WokinShopash commented on encryptor.py
> +def ceaser(input_text, key_=0):
Что-то пошло не так с именем бедного императора

2020-04-21 22:21 UTC, WokinShopash commented on encryptor.py
> +parser = argparse.ArgumentParser(description='Encoder')
При таком подходе в режимах будут пристутствовать незначащщие аргументы, что приведет к запутыванию пользователя.
Лучше разобрать аргументы через subparsers

2020-04-21 22:21 UTC, WokinShopash commented on encryptor.py
> +            result += chr((tmp_order + key_) % 26 + ord('a'))
chr/ord - нерасширяемо, переделать на фиксированный алфавит

2020-04-21 22:21 UTC, WokinShopash commented on encryptor.py
> +    alphabet = "abcdefghijklmnopqrstuvwxyz"
Импортировать из модуля string

2020-04-21 22:21 UTC, WokinShopash commented on encryptor.py
> +    best_stats = 20000000000000
float("inf") или None

2020-05-04 16:11 UTC, tardis-forever requested changes

2020-05-04 16:11 UTC, tardis-forever commented on encryptor.py
> +def caeser(input_text, key_=0):
Почему здесь не просто `key`?

2020-05-04 16:11 UTC, tardis-forever commented on encryptor.py
> +    uppercase_eng = string.ascii_uppercase
Это используется в нескольких функциях - возможно, стоит вынести в константы

2020-05-04 16:11 UTC, tardis-forever commented on encryptor.py
> +            result += uppercase_eng[(ord(sym) - ord(uppercase_eng[0]) +
Решение все еще зависит от численных кодов символов - уже просили это исправить

2020-05-04 16:11 UTC, tardis-forever commented on encryptor.py
> +            reversed_key += lowercase_eng[len(lowercase_eng) -
Не надо конкатенировать строки в цикле, они неизменяемые и каждый раз заново создаются

2020-05-04 16:11 UTC, tardis-forever commented on encryptor.py
> +        tmp_ord = ord(sym) - ord(lowercase_eng[0])
Здесь опять коды символов

2020-05-04 16:11 UTC, tardis-forever commented on encryptor.py
> +            key_num += 1
С заменой одного алфавита на другой код точно такой же, как в предыдущей ветке `if`. (И в предыдущих функциях тоже)

2020-05-04 16:11 UTC, tardis-forever commented on encryptor.py
> +        if x.islower() or x.isupper():
`isalpha`

2020-05-04 16:11 UTC, tardis-forever commented on encryptor.py
> +    sum = float(0)
`0.`

2020-05-04 16:11 UTC, tardis-forever commented on encryptor.py
> +    for x in stats_1.keys():
Можно без `keys()`, просто `for x in stats`

2020-05-04 16:11 UTC, tardis-forever commented on encryptor.py
> +    best_index = 27
Магическая константа

2020-05-04 16:11 UTC, tardis-forever commented on encryptor.py
> +    for i in range(1, 27):
Здесь тоже

2020-05-04 16:11 UTC, tardis-forever commented on encryptor.py
> +        stats_tmp = count_stat(caeser(str(encoded_text), i))
Зачем каст к строке?

2020-05-04 16:11 UTC, tardis-forever commented on encryptor.py
> +        stats_tmp = count_stat(caeser(str(encoded_text), i))
И, кажется, Цезарь пишется по-другому

2020-05-04 16:11 UTC, tardis-forever commented on encryptor.py
> +        difference = minus_stats(default_stats_, stats_tmp)
Можно заново не пересчитывать статистику, а вычислять ее на основе предыдущей

2020-05-04 16:11 UTC, tardis-forever commented on encryptor.py
> +if args.mode == 'encode' or args.mode == 'decode' or args.mode == 'hack':
Ввод и вывод сильно дублируется

2020-05-04 16:11 UTC, tardis-forever commented on encryptor.py
> +output_string = ''
Не надо делать лишних переменных в глобальной области видимости

2020-05-04 16:11 UTC, tardis-forever commented on encryptor.py
> +if args.mode == 'encode' or args.mode == 'decode' or args.mode == 'hack':
Всю обработку стоит обернуть в `main`

2020-05-12 10:09 UTC, tardis-forever requested changes

2020-05-12 10:09 UTC, tardis-forever commented on encryptor.py
> +            return sym
У листов есть встроенные методы поиска

2020-05-12 10:09 UTC, tardis-forever commented on encryptor.py
> +        if x.islower() or x.isupper():
Чем предложенный вариант не устраивает?

2020-05-12 10:09 UTC, tardis-forever commented on encryptor.py
> +            iteration += 1
Дублирование

2020-05-12 10:09 UTC, tardis-forever commented on encryptor.py
> +    return ans
Можно не создавать новый словарь каждый раз, а вычислять сдвинутые значения частот на лету

2020-05-12 10:09 UTC, tardis-forever commented on encryptor.py
> +    if hasattr(args, 'cipher'):
Лучше добавлять значения по умолчанию - например, `None`, как индикатор отсутсвия значения

2020-05-19 13:02 UTC, TieBeTie commented on encryptor.py
> +    if hasattr(args, 'cipher'):
ето как

2020-05-19 13:04 UTC, TieBeTie commented on encryptor.py
> +    if hasattr(args, 'cipher'):
> Лучше добавлять значения по умолчанию - например, `None`, как индикатор отсутсвия значения

вы имеете в виду в любом случае добавить в Namespace args атрибут cipher, значение которого None?

2020-05-19 13:26 UTC, tardis-forever commented on encryptor.py
> +    if hasattr(args, 'cipher'):
Да, примерно так

2020-05-19 19:12 UTC, tardis-forever requested changes

2020-05-19 19:12 UTC, tardis-forever commented on encryptor.py
> +                             len(uppercase_eng)]
Дублирует случай выше, стоит вынести определение алфавита в `if`, а потом применить к нему такую операцию

2020-05-19 19:12 UTC, tardis-forever commented on encryptor.py
> +        return uppercase_eng[len(uppercase_eng) - (ind_uppercase(letter))]
Здесь тоже

2020-05-19 19:12 UTC, tardis-forever commented on encryptor.py
> +    iteration += 1
`int` передаются по значению, это `+=`  ничего не изменит

2020-05-19 19:12 UTC, tardis-forever commented on encryptor.py
> +            text_file.close()
Дублирование операций ввода-вывода

2020-05-20 11:07 UTC, tardis-forever commented
Зачтено

2020-08-14 19:14 UTC, merged